<a href="https://colab.research.google.com/github/zaccesss/DG1AID-Labs/blob/main/DG1AID_Lab_Week1_Colab_Python_II_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**CS2IAI Introduction to Artificial Intelligence**

Prepaped by Dr. Shereen Fouad

**Welcome! In this practical session we will learn about the basic syntax and usage of Python as well as the NumPy library**


Read through the notebook to see how python commands are being implemeted. Then answer the exercise questions. Your answers should be added in code cells.

# **Notebook**

Notebooks are a great way to mix executable code with rich contents (HTML, images, equations written in LaTeX). Colab allows to run notebooks on the cloud for free without any prior installation, while leveraging the power of GPUs.

The document that you are reading is not a static web page, but an interactive environment called a notebook, that lets you write and execute code. Notebooks consist of so-called code cells, blocks of one or more Python instructions. For example, here is a code cell that stores the result of a computation (the number of seconds in a day) in a variable and prints its value:


In [1]:
seconds_in_a_day = 24 * 60 * 60
seconds_in_a_day

86400

Click on the "play" button to execute the cell. You should be able to see the result. Alternatively, you can also execute the cell by pressing Ctrl + Enter if you are on Windows / Linux or Command + Enter if you are on a Mac.

Variables that you defined in one cell can later be used in other cells:

In [2]:
seconds_in_a_week = 7 * seconds_in_a_day
seconds_in_a_week

604800

Note that the order of execution is important. For instance, if we do not run the cell storing seconds_in_a_day beforehand, the above cell will raise an error, as it depends on this variable. To make sure that you run all the cells in the correct order, you can also click on "Runtime" in the top-level menu, then "Run all".

## **Python Basics** (review from lab 1)

**Arithmetic operations**

Python supports the usual arithmetic operators: + (addition), * (multiplication), / (division), ** (power), // (integer division).

**Numbers**

There are two main types of number in Python:
1. Floats (or floating point numbers)
2. Integers

In [3]:
value = 123.1
print(value)
value = 10
print(value)

123.1
10


**String**

They are a way of representing normal human words inside a Python script. Strings start and end with double quotes (") e.g.,

In [4]:
# Strings
data = 'hello world'
print(data[0])
print(len(data))
print(data)

h
11
hello world


**Boolean**
True or False

In [5]:
# Boolean
a = True
b = False
print(a, b)

True False


**Flow Control**

Conditionals are a way to execute code depending on whether a condition is True or False.
There are **three** main types of flow control that you need to learn: **If-Then-Else** conditions, **For-Loops** and **While-Loops**.

If-Then-Else Condition Example

In [6]:
value = 99
if value >= 99:
	print('That is fast')
elif value > 200:
	print('That is too fast')
else:
	print('That that is safe')

That is fast


**Loops**

Loops are a way to execute a block of code multiple times. There are two main types of loops: **while loops and for loops.**

In [7]:
# While-Loop
i = 0
while i < 10:
	print(i)
	i += 1

0
1
2
3
4
5
6
7
8
9


In [8]:
# For-Loop
for i in range(10):
	print(i)

0
1
2
3
4
5
6
7
8
9


**Data Structures**

There are three data structures in Python that you will find the most used and useful. They are **tuples**, **lists** and **dictionaries**.

**Tuple Example**

Tuples are read-only collections of items.

In [9]:
a = (1, 2, 3)
print(a)

(1, 2, 3)


**List Example**

Lists use the square bracket notation and can be index using array notation.

In [10]:
mylist = [1, 2, 3]
print("Zeroth Value: %d" % mylist[0])
mylist.append(4)
print("List Length: %d" % len(mylist))
for value in mylist:
	print(value)

Zeroth Value: 1
List Length: 4
1
2
3
4


**Dictionary Example**

Dictionaries are mappings of names to values, like a map. Note the use of the curly bracket notation.

In [11]:
mydict = {'a': 1, 'b': 2, 'c': 3}
print("A value: %d" % mydict['a'])
mydict['a'] = 11
print("A value: %d" % mydict['a'])
print("Keys: %s" % mydict.keys())
print("Values: %s" % mydict.values())
for key in mydict.keys():
	print(mydict[key])

A value: 1
A value: 11
Keys: dict_keys(['a', 'b', 'c'])
Values: dict_values([11, 2, 3])
11
2
3


**Functions**

To improve code readability, it is common to separate the code into different blocks, responsible for performing precise actions: **functions**. A function takes some inputs and process them to return some outputs.

The example below defines a new function to calculate the sum of two values and calls the function with two arguments.

In [12]:
# Sum function
def mysum(x, y):
	return x + y

# Test sum function
print(mysum(1, 3))

4


**Classes**

The syntax for defining classes in Python is straightforward:

In [13]:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

p1 = Person("John", 36)

print(p1.name)
print(p1.age)

John
36


# **Exercise 1**
**Exercise 1.1**

Using a conditional, carete a function called **relu** that takes an input x and returns a values. The function will be defined as follows:

relu(x)=x,

if x≥0, relu(x)=x, 0, otherwise

Test your function as follows to see whether it returns the expected value or not.  e.g **relu(-3)**


In [14]:
def relu(x):
    if x >= 0:        # if x is zero or positive
        return x      # return x as it is (pass it through unchanged)
    else:             # if x is negative
        return 0      # squash it to 0

print(relu(5))   # testing with a positive number - should return 5
print(relu(-3))  # testing with a negative number - should return 0



5
0


**Exercise 1.2**

Write a Python function to find the **Max of two numbers** and another one to find the **Max of three numbers**.

In [15]:
def max_of_two(a, b):
    if a > b:       # if a is bigger than b
        return a    # return a as it is the largest
    else:           # otherwise b is bigger or they are equal
        return b    # return b as it is the largest

print(max_of_two(3, 7))   # should print 7
print(max_of_two(10, 4))  # should print 10
print(max_of_two(5, 5))   # should print 5 - equal numbers

def max_of_three(a, b, c):
    if a > b and a > c:   # if a is bigger than both b and c
        return a          # a is the largest
    elif b > a and b > c: # if b is bigger than both a and c
        return b          # b is the largest
    else:                 # otherwise c must be the largest
        return c          # c is the largest

print(max_of_three(3, 7, 10))   # should print 10
print(max_of_three(10, 4, 8))   # should print 10
print(max_of_three(5, 5, 5))    # should print 5

7
10
5
10
10
5


# **NumPy Crash Course**
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

NumPy provides the foundation data structures and operations for SciPy. These are arrays (ndarrays) that are efficient to define and manipulate.

**Create Array**

To use Numpy, we first need to import the numpy package:

In [16]:
# define an array
import numpy
mylist = [[1, 2, 3], [3, 4, 5]]
myarray = numpy.array(mylist)
print(myarray)
print(myarray.shape)

[[1 2 3]
 [3 4 5]]
(2, 3)


**Access Data**

Array notation and ranges can be used to efficiently access data in a NumPy array.

In [17]:
# access values
print("First row: %s" % myarray[0])
print("Last row: %s" % myarray[-1])
print("Specific row and col: %s" % myarray[0, 2])
print("Whole col: %s" % myarray[:, 2])

First row: [1 2 3]
Last row: [3 4 5]
Specific row and col: 3
Whole col: [3 5]


**Arithmetic**

NumPy arrays can be used directly in arithmetic.

In [18]:
# arithmetic
import numpy as np
myarray1 = np.array([2, 2, 2])
myarray2 = np.array([3, 3, 3])
print("Addition: %s" % (myarray1 + myarray2))
print("Multiplication: %s" % (myarray1 * myarray2))

Addition: [5 5 5]
Multiplication: [6 6 6]


**Slicing and masking**

Like Python lists, NumPy arrays support slicing

We can create an array which includes a range of values




In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


We can also select only certain elements from the array

In [20]:
np.arange(10)[5:]

array([5, 6, 7, 8, 9])

We can also select only certain elements from the array

In [21]:
x = np.arange(10)
mask = x >= 5
x[mask]

array([5, 6, 7, 8, 9])

# **Exercise 2**

**Exercise 2.1**

Write a NumPy program to create an array of the integers from 30 to 70.

In [22]:
import numpy as np

# create an array of integers from 30 to 70 inclusive
# np.arange goes up to but not including the stop number, so we use 71
print(np.arange(30, 71))

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


**Exercise 2.2**

Rewrite the relu function (see Python section) using np.maximum. Check that it works on both a single value and on an array of values.

In [23]:
import numpy as np

def relu_numpy(x):
    return np.maximum(0, x)  # returns x if positive, 0 if negative

# test on a single value
print(relu_numpy(5))    # should print 5
print(relu_numpy(-3))   # should print 0

# test on a whole array at once - this is the superpower of numpy!
arr = np.array([3, -1, 5, -2, 7])
print(relu_numpy(arr))  # should print [3 0 5 0 7]

5
0
[3 0 5 0 7]


**Exercise 2.3**

Write a NumPy program to find common values between two arrays.

Use this builtin function **numpy.intersect1d** [more information about this builtin function can be foud here](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]

In [24]:
import numpy as np

# define the two arrays
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([10, 30, 40])

# find and print the values that appear in both arrays
print(np.intersect1d(array1, array2))  # should print [10 40]

[10 40]


**Exercise 2.4**

Write a NumPy program to create a 3x4 matrix filled with values ​​from 10 to 21.

In [25]:
import numpy as np

# create a 3x4 matrix filled with values from 10 to 21
# arange goes up to but not including 22, so we get 10 to 21
# reshape turns the flat array into a 3 row, 4 column matrix
print(np.arange(10, 22).reshape(3, 4))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


**Exercise 2.5**

Write a Python script to calculate the following statistical values from a NumPy array of size 10 with random values between 1 and 50:

*   Standard deviation
*   Variance
*   Median
*   75th percentile

In [26]:
import numpy as np

# create an array of 10 random integers between 1 and 50
a = np.random.randint(1, 51, size=10)
print("Array:", a)

# standard deviation - how spread out the numbers are from the average
print("Standard deviation:", np.std(a))

# variance - standard deviation squared, another measure of spread
print("Variance:", np.var(a))

# median - the middle value when sorted
print("Median:", np.median(a))

# 75th percentile - 75% of values fall below this number
print("75th percentile:", np.percentile(a, 75))

Array: [32  9 47 47 33 11 31  4 36  4]
Standard deviation: 16.032467059064867
Variance: 257.04
Median: 31.5
75th percentile: 35.25


# More Advanced
**Exercise 2.6**

Create a 6x6 NumPy array with a checkerboard pattern (alternating 1s and 0s).

In [27]:
import numpy as np

# create a 6x6 grid of zeros
board = np.zeros((6, 6), dtype=int)

# fill in the 1s at alternating positions to create checkerboard pattern
board[0::2, 0::2] = 1   # even rows, even columns get a 1
board[1::2, 1::2] = 1   # odd rows, odd columns get a 1

print(board)

[[1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]]


**Exercise 2.6**

Create a 1D NumPy array ([10, -5, 3, -2, 15, -7]). Replace all negative values with 0, without modifying the original array.

In [28]:
import numpy as np

# create the original array
original = np.array([10, -5, 3, -2, 15, -7])

# make a copy so the original is not modified
modified = original.copy()

# replace all negative values in the copy with 0
modified[modified < 0] = 0

# print both to prove the original is unchanged
print("Original:", original)   # should still have negatives
print("Modified:", modified)   # should have 0s instead of negatives

Original: [10 -5  3 -2 15 -7]
Modified: [10  0  3  0 15  0]
